<?php 

//System Configurations (Auto Generated file)
$config_http_script_dir = "";
$config_default_charset = "UTF-8";
$config_skin = "default";
$config_useutf8 = "0";
$config_utf8html = "0";
$config_use_wysiwyg = "ckeditor";
$config_date_adjust = "0";
$config_smilies = "smile,wink,wassat,tongue,laughing,sad,angry,crying";
$config_auto_archive = "no";
$config_allow_registration = "yes";
$config_ban_attempts = "3";
$config_use_replacement = "0";
$config_registration_level = "4";
$config_ipauth = "1";
$config_xss_strict = "1";
$config_userlogs = "1";
$config_use_avatar = "no";
$config_reverse_active = "no";
$config_full_popup = "no";
$config_full_popup_string = "HEIGHT=400,WIDTH=650,resizable=yes,scrollbars=yes";
$config_show_comments_with_full = "yes";
$config_timestamp_active = "Y M d";
$config_backup_news = "yes";
$config_use_captcha = "1";
$config_use_rater = "0";
$config_auto_wrap = "44";
$config_reverse_comments = "yes";
$config_flood_time = "0";
$config_comment_max_long = "1500";
$config_comments_per_page = "50";
$config_only_registered_comment = "no";
$config_allow_url_instead_mail = "yes";
$config_comments_popup = "no";
$config_comments_popup_string = "HEIGHT=300,WIDTH=650,resizable=yes,scrollbars=yes";
$config_show_full_with_comments = "yes";
$config_timestamp_comment = "d M Y h:i a";
$config_notify_status = "disabled";
$config_notify_registration = "no";
$config_notify_comment = "no";
$config_notify_unapproved = "no";
$config_notify_archive = "no";
$config_notify_postponed = "no";
$config_notify_email = "";
$config_use_fbcomments = "no";
$config_fb_i18n = "en_US";
$config_fb_inactive = "no";
$config_fb_comments = "4";
$config_fb_box_width = "420";
$config_fb_appid = "";
?>